### ISSUE TITLE
Forward webapp-terminating messages immediately

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-gateway#48] opened 2017-03-01 08:02 UTC
_Consider_ forwarding webapp-terminating messages immediately that they are received to medic-gateway.  Consider that any autoreplies triggered will likely still not be available until the next poll is made (depending on how/where/when api/webapp/sentinel generates these replies).

**Comment by garethbowen** [comment] 2020-03-03 06:19
@SCdF This is a duplicate of #138 right?

**Comment by SCdF** [comment] 2020-03-04 04:32
Yes! 

> Consider that any autoreplies triggered will likely still not be available

Is also covered by us making sentinel sync for SMS.

**Closed by SCdF** 2020-03-04 04:32 UTC
Labels: Type: Improvement
